name: .NET Build and Release

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Create Release Asset
        if: github.event_name == 'release'
        run: |
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true -o publish
          
          7z a -tzip "${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-win-x64.zip" "./publish/*"

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-win-x64.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-win-x64.zip
          asset_content_type: application/zip